export default {
  blue: 'blue',
  cyan: 'cyan',
  danger: 'danger',
  dark: 'dark',
  fuchsia: 'fuchsia',
  gray: 'gray',
  'gray-dark': 'gray',
  green: 'green',
  indigo: 'indigo',
  info: 'info',
  light: 'light',
  lightblue: 'lightblue',
  lime: 'lime',
  maroon: 'maroon',
  navy: 'navy',
  olive: 'olive',
  purple: 'purple',
  red: 'red',
  secondary: 'secondary',
  success: 'success',
  teal: 'teal',
  warning: 'warning',
  white: 'white',
  yellow: 'yellow'
}
